name: Flipkart Price Tracker

on:
  schedule:
    - cron: "*/5 * * * *"   # ⏰ every 5 minutes
  workflow_dispatch:         # allow manual trigger

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run tracker
        run: python tracker.py
